ds_name: 'diabetis' # dataset name
data_batch_size: 614 # full train ds size
clip_alpha: 8.0
random_key: 'diabetis'
batch_size: 1024
layer_width: 128
n_layers: 2
pretrain_lr: 1.e-3
n_jko_steps: 16 # number of jko steps to perform
lr: 5.e-5
dt: 0.1 # jko time interval
n_step_iterations: 6000 # number of optimization iterations per jko step
n_max_prop: 1024
n_eval_samples: 4096
experiment_name: 'diabetis_data_posterior'
experiment_dir : './results/data_posterior'
