ds_name: 'image' # dataset name
data_batch_size: 512
clip_alpha: 8.0
random_key: 'image'
batch_size: 512
layer_width: 512
n_layers: 2
pretrain_lr: 1.e-3
n_jko_steps: 5 # number of jko steps to perform
lr: 5.e-5
dt: 0.1 # jko time interval
n_step_iterations: 5000 # number of optimization iterations per jko step
n_max_prop: 512
n_eval_samples: 4096
experiment_name: 'image_data_posterior'
experiment_dir : './results/data_posterior'
