ds_name: 'splice' # dataset name
data_batch_size: 512
clip_alpha: 8.0
random_key: 'splice'
batch_size: 512
layer_width: 512
n_layers: 2
pretrain_lr: 1.e-4
n_jko_steps: 5 # number of jko steps to perform
lr: 2.e-3
dt: 0.1 # jko time interval
n_step_iterations: 2000 # number of optimization iterations per jko step
n_max_prop: 512
n_eval_samples: 4096
experiment_name: 'splice_data_posterior'
experiment_dir : './results/data_posterior'
